<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><p>Hello RW</p></title>

</head>
<body>
    <h1> To </h1>
    <p><ul><li>VOeg een item uit module toe bv SNellink naar SALES </li>
    <p><li>VOeg meer submenus toe     </li>  
    <p><li>VOeg booleans en anderer functies toe     </li> 
    <p><li>Laat versie zien ergens in menu   </li>   
</body>
</html>